### ISSUE TITLE
燒錄失敗

### ISSUE THREAD

**Issue by tingwei0509** [mickey9910326/ASA_HMI_Data_Agent#7]
燒錄失敗
ASA_loader 不會關閉
直接使用指令沒問題

**Comment by tingwei0509** [comment]
應該是ASA_loader的問題  
使用HMI資料夾內部的ASA LOADER使用指令也失敗

**Comment by tingwei0509** [comment]
![image](https://user-images.githubusercontent.com/30106311/37322557-3d0ab0ac-26b9-11e8-8ee4-76219e1614a6.png)

**Comment by tingwei0509** [comment]
![image](https://user-images.githubusercontent.com/30106311/37322589-775f107c-26b9-11e8-8d42-2b8656ca6eff.png)

**Comment by mickey9910326** [comment]
DONE
